vCenter = "vc01.ldc.int"
userName = "administrator@vsphere.local"
password = "VMware1!"
datacenter = "DR-Sky"
datastore = "LSI-SSD00.local"
cluster = "DR-Main"
network = "V1720"
template = "CentOS7-DR"