variable "count" {}
variable "prefix" {}
variable "folder" {}
variable "CPU" {}
variable "mem" {}
variable "start_val" {}
variable "ipv4" {}
variable subnet {}
variable gateway {}
variable domain {}
variable dns_servers {}
variable vCenter {}
variable userName {}
variable password {}
variable datacenter {}
variable datastore {}
variable cluster {}
variable network {}
variable template {}
